---
- name: "SPreg - Prepare main folder for configuration"
  file:
    path: "{{ spreg_config_destination }}"
    state: directory
    mode: 0640
  tags:
    - configuration

- name: "SPreg - Prepare subfolders for configuration"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0640
    group: root
  loop:
    - "{{ spreg_config_destination }}/attrs"
  tags:
    - configuration

- name: "Spreg - Copy configuration files"
  template:
    src: "templates/spreg/{{ item }}.jinja2"
    dest: "{{ spreg_config_destination }}/{{ item }}"
    backup: yes
    owner: root
    group: root
    mode: 0640
  loop: "{{ spreg_config_list_of_configuration_files }}"
  tags:
    - configuration

- name: "SPreg - download code"
  git:
    repo: "{{ spreg_source_code_repository_URL }}"
    dest: "{{ spreg_source_code_dest }}"
    version: "{{ spreg_source_code_version }}"
    force: yes
    update: yes
  tags:
    - upgrade

- name: "SPReg - rebuild"
  command: "./mvnw clean package -Pbuild-ui -Dangular.api.url={{ spreg_app_angular_api_url }}"
  args:
    chdir: "{{ spreg_source_code_dest }}"
  tags:
    - upgrade

- name: "SPreg - restart systemd unit"
  command: "systemctl restart spreg.service"
  tags:
    - upgrade
    - restart

- name: "flush handlers"
  meta: flush_handlers
