---
- name: "SPreg - Install packages"
  apt:
    name:
      - openjdk-11-jdk
      - maven
      - curl
      - git
    update_cache: yes
  tags:
    - install

- name: "SPreg - Set working environment"
  import_role:
    name: cesnet.proxy_env

- name: "SPreg - Set firewall"
  import_role:
    name: cesnet.firewall
  vars:
    firewall_open_ssh_ports: "{{ spreg_firewall_open_ssh_ports }}"
    firewall_open_tcp_ports: "{{ spreg_firewall_open_tcp_ports }}"

- name: "SPreg - Set up unattended upgrades"
  import_role:
    name: "cesnet.unattended_upgrades"
  vars:
    unattended_upgrades_origin_patterns: "{{ spreg_unattended_upgrades_origin_patterns }}"
    unattended_upgrades_blacklist: "{{ spreg_unattended_upgrades_blacklist }}"
    root_email_address: "{{ spreg_unattended_upgrades_mail_address }}"

- name: "SPreg - Set up Yubikeys"
  import_role:
    name: cesnet.yubikeys
  vars:
    other_sudo_user: ""
    yubikey_users: "{{ spreg_yubikey_users }}"
    yubikey_id: "{{ spreg_yubikey_id }}"
    yubikey_key: "{{ spreg_yubikey_key }}"
    yubikey_lognames: "{{ spreg_yubikey_lognames }}"
    sudo_root_lognames: "{{ spreg_sudo_root_lognames }}"
    sudo_other_lognames: "{{ spreg_sudo_perun_lognames }}"

- name: "SPreg - Set up monitoring by MetaCentrum's Nagios"
  import_role:
    name: cesnet.metacentrum_monitoring
  vars:
    monitoring_check_mk_packages: "{{ spreg_monitoring_check_mk_packages }}"
    monitoring_check_mk_local_scripts_by_template: "{{ spreg_monitoring_check_mk_local_scripts_by_template }}"
    monitoring_check_mk_local_scripts_file: "{{ spreg_monitoring_check_mk_local_scripts_file }}"
    monitoring_check_mk_plugins_by_template: "{{ spreg_monitoring_check_mk_plugins_by_template }}"
    monitoring_check_mk_plugins_file: "{{ spreg_monitoring_check_mk_plugins_file }}"

- name: "SPreg - Install sendmail"
  import_role:
    name: cesnet.sendmail
  vars:
    sendmail_relays: "{{ spreg_sendmail_relays }}"

- name: "SPreg - Install and configure MariaDB"
  import_role:
    name: cesnet.mariadb
  vars:
    mariadb_root_password: "{{ spreg_mariadb_root_password }}"
    mariadb_databases_to_create: "{{ spreg_mariadb_databases_to_create }}"
    mariadb_users_to_create: "{{ spreg_mariadb_users_to_create }}"
    mariadb_users_privileges: "{{ spreg_mariadb_users_privileges }}"
    mariadb_scripts: "{{ spreg_mariadb_scripts }}"

- name: "MARIADB_DATABASE_BACKUP - Copy backup script"
  copy:
    src: "backup_database.sh"
    dest: "/root/backup_database.sh"
    mode: 0700

- name: "MARIADB_DATABASE_BACKUP - Set daily cron job"
  cron:
    name: "mariadb_database_backup"
    special_time: daily
    user: root
    job: "/root/backup_database.sh > /dev/null 2>&1"

- name: "SPreg - Install and configure Shibboleth"
  import_role:
    name: cesnet.shibboleth_sp
  vars:
    shibboleth_hostname: "{{ spreg_shibboleth_hostname }}"
    shibboleth_sp_entity_id: "{{ spreg_shibboleth_sp_entity_id }}"
    shibboleth_template_attribute_map_allow_urn_oid_attributes: "{{ spreg_shibboleth_template_attribute_map_allow_urn_oid_attributes }}"
    shibboleth_template_attribute_map_allow_urn_mace_attributes: "{{ spreg_shibboleth_template_attribute_map_allow_urn_mace_attributes }}"
    shibboleth_template_attribute_map_allow_schac_attributes: "{{ spreg_shibboleth_template_attribute_map_allow_schac_attributes }}"
    shibboleth_template_attribute_map_custom_attributes: "{{ spreg_shibboleth_template_attribute_map_custom_attributes }}"
    shibboleth_template_sp_entity_id: "{{ spreg_shibboleth_template_sp_entity_id }}"
    shibboleth_template_remote_users: "{{ spreg_shibboleth_template_remote_users }}"
    shibboleth_template_attribute_prefix: "{{ spreg_shibboleth_template_attribute_prefix }}"
    shibboleth_template_idp_entity_id: "{{ spreg_shibboleth_template_idp_entity_id }}"
    shibboleth_template_metadata_url: "{{ spreg_shibboleth_template_metadata_url }}"
    shibboleth_template_metadata_backup_file: "{{ spreg_shibboleth_template_metadata_backup_file }}"

- name: "SPreg - Install and configure Apache"
  import_role:
    name: cesnet.apache2
  vars:
    apache_packages: "{{ spreg_apache_packages }}"
    apache_modules: "{{ spreg_apache_modules }}"
    apache_remove_sites: "{{ spreg_apache_remove_sites }}"
    apache_create_sites: "{{ spreg_apache_create_sites }}"
    apache_enable_sites: "{{ spreg_apache_enable_sites }}"

- name: "SPreg - set Apache TLS"
  import_role:
    name: cesnet.apache_tls
  vars:
    certs_dir: "{{ spreg_certs_dir }}"

- name: "SPreg - Install Tomcat"
  import_role:
    name: cesnet.tomcat
  vars:
    tomcat_service_group: ""
    tomcat_readonly_paths:
      - "/etc/spreg"
    tomcat_readwrite_paths:
      - "/var/log/spreg"

- name: "SPreg - deploy"
  import_tasks: spreg_deploy.yml
  tags:
    - spreg_deploy

- name: "flush handlers"
  meta: flush_handlers
