---
- name: "SPreg - Prepare main folder for configuration"
  file:
    path: "{{ spreg_config_destination }}"
    state: directory
    mode: 0640
  tags:
    - spreg_deploy_conf

- name: "SPreg - Prepare subfolders for configuration"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0640
    group: root
  loop:
    - "{{ spreg_config_destination }}/attrs"
  tags:
    - spreg_deploy_conf

- name: "Spreg - Copy configuration files"
  template:
    src: "templates/spreg/{{ item }}.jinja2"
    dest: "{{ spreg_config_destination }}/{{ item }}"
    backup: yes
    owner: root
    group: root
    mode: 0640
  loop: "{{ spreg_config_list_of_configuration_files }}"
  tags:
    - spreg_deploy_conf

- name: "SPreg - download code"
  git:
    repo: "{{ spreg_source_code_repository_URL }}"
    dest: "{{ spreg_source_code_dest }}"
    version: "{{ spreg_source_code_version }}"
    force: yes
    update: yes
  tags:
    - spreg_upgrade

- name: "SPReg - rebuild"
  command: "./mvnw clean package -Pui -Dangular.api.url=\"{{ spreg_app_angular_api_url }}\""
  args:
    chdir: "{{ spreg_source_code_dest }}"
  tags:
    - spreg_upgrade

- name: "SPreg - restart systemd unit"
  register: spreg_systemd_res
  systemd:
    name: spreg.service
    state: restarted
  tags:
    - spreg_upgrade
    - spreg_restart

- name: "SPReg - check systemd unit is running"
  fail:
    msg: "spreg.service is not active"
  when: spreg_systemd_res['status']['ActiveState'] != 'active'
  tags:
    - spreg_upgrade
    - spreg_restart

- name: "flush handlers"
  meta: flush_handlers
